language: go

matrix:
  include:
    - go: 1.10.x
    - go: 1.11.x
    - go: 1.12.x

before_install:
  - mkdir -p bin
  - curl -Lso bin/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.3/shellcheck
  - chmod +x bin/shellcheck
script:
  - PATH=$PATH:$PWD/bin go test -v ./...
  - go build